env:
  browser: true
  es2021: true
  jquery: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: 'script'
rules:
  linebreak-style: 0
  indent: ['warn', 2, { SwitchCase: 1 }]
  strict: 0
  spaced-comment: ['warn']
  eol-last: ['warn']
  no-alert: ['warn']
  no-extra-semi: ['warn']
  no-trailing-spaces: ['warn']
  no-nested-ternary: 0
  no-plusplus: 0
  padded-blocks: 0
  radix: 0
