env:
  browser: true
  es2021: true
  jquery: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: 'script'
reportUnusedDisableDirectives: true
plugins:
  - document-write
rules:
  linebreak-style: 0
  operator-linebreak: 0
  indent: ['warn', 2, { SwitchCase: 1 }]
  strict: ['warn', 'global']
  spaced-comment: ['warn']
  eol-last: ['warn']
  no-alert: ['warn']
  no-extra-semi: ['warn']
  no-trailing-spaces: ['warn']
  no-restricted-globals: ['warn']
  no-restricted-syntax: 0
  no-nested-ternary: 0
  no-plusplus: 0
  no-else-return: 0
  no-console: ['warn']
  padded-blocks: 0
  radix: 0
  lines-around-directive: 0
  guard-for-in: 0
  operator-assignment: ['warn']
  quotes: ['warn']
  document-write/no-document-write: ['warn']
